# Generated by Django 4.1.4 on 2022-12-20 01:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the model', max_length=64)),
                ('target_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mappers.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the field', max_length=64)),
                ('type', models.CharField(choices=[('OBJECT', 'Object'), ('ARRAY', 'Array'), ('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean')], help_text='Name of the field type', max_length=32)),
                ('choices', models.JSONField(help_text='List of enum choices for this field', null=True)),
                ('list_item_type', models.CharField(choices=[('OBJECT', 'Object'), ('ARRAY', 'Array'), ('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean')], help_text="Name of list item's type", max_length=32)),
                ('model', models.ForeignKey(help_text='Reference to the model that this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mappers.model')),
                ('object_model', models.ForeignKey(help_text="Reference to a model if this field's value is another model", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mappers.model')),
                ('target_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mappers.field')),
            ],
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('model_id', 'name'), name='unique_model_and_field_name'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['OBJECT', 'ARRAY', 'STRING', 'NUMBER', 'BOOLEAN'])), name='mappers_field_type_valid'),
        ),
    ]
