# Generated by Django 4.1.4 on 2022-12-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='field',
            name='mappers_field_type_valid',
        ),
        migrations.AddField(
            model_name='model',
            name='is_remote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='choices',
            field=models.JSONField(blank=True, help_text='List of enum choices for this field', null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='list_item_type',
            field=models.CharField(blank=True, choices=[('OBJECT', 'Object'), ('ARRAY', 'Array'), ('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('UNKNOWN', 'Unknown')], help_text="Name of list item's type", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='object_model',
            field=models.ForeignKey(blank=True, help_text="Reference to a model if this field's value is another model", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mappers.model'),
        ),
        migrations.AlterField(
            model_name='field',
            name='target_field',
            field=models.ForeignKey(blank=True, help_text='Reference to the target field that this remote field maps to', null=True, on_delete=django.db.models.deletion.CASCADE, to='mappers.field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('OBJECT', 'Object'), ('ARRAY', 'Array'), ('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('UNKNOWN', 'Unknown')], help_text='Name of the field type', max_length=32),
        ),
        migrations.AlterField(
            model_name='model',
            name='target_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mappers.model'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['OBJECT', 'ARRAY', 'STRING', 'NUMBER', 'BOOLEAN', 'UNKNOWN'])), name='mappers_field_type_valid'),
        ),
    ]
