# Generated by Django 4.1.4 on 2022-12-21 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappers', '0002_remove_field_mappers_field_type_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('UPPERCASE', 'Uppercase'), ('LOWERCASE', 'Lowercase'), ('CAPITALIZE', 'Captalize'), ('STRING_TO_FLOAT', 'String to Float'), ('STRING_TO_INTEGER', 'String to Integer'), ('STRING_TO_BOOLEAN', 'String to Boolean'), ('NUMBER_TO_STRING', 'Number to String')], help_text='Name of the transformer type', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='field',
            name='mappers_field_type_valid',
        ),
        migrations.AlterField(
            model_name='field',
            name='list_item_type',
            field=models.CharField(blank=True, choices=[('OBJECT', 'Object'), ('LIST', 'List'), ('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('UNKNOWN', 'Unknown')], help_text="Name of list item's type", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('OBJECT', 'Object'), ('LIST', 'List'), ('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('UNKNOWN', 'Unknown')], help_text='Name of the field type', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['OBJECT', 'LIST', 'STRING', 'NUMBER', 'BOOLEAN', 'UNKNOWN'])), name='mappers_field_type_valid'),
        ),
        migrations.AddField(
            model_name='field',
            name='transformer',
            field=models.ForeignKey(blank=True, help_text='Reference to the transformer for this field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mappers.transformer'),
        ),
    ]
