# Generated by Django 4.1.4 on 2023-01-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappers', '0004_fieldmap_map_modelmap_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Mapper',
        ),
        migrations.RemoveConstraint(
            model_name='fieldmap',
            name='mappers_fieldmap_unique_source_map_target',
        ),
        migrations.RemoveConstraint(
            model_name='modelmap',
            name='mappers_modelmap_unique_source_map_target',
        ),
        migrations.RenameField(
            model_name='fieldmap',
            old_name='map',
            new_name='mapper',
        ),
        migrations.RenameField(
            model_name='modelmap',
            old_name='map',
            new_name='mapper',
        ),
        migrations.AddConstraint(
            model_name='fieldmap',
            constraint=models.UniqueConstraint(fields=('source_field', 'mapper', 'target_field'), name='mappers_fieldmap_unique_source_mapper_target'),
        ),
        migrations.AddConstraint(
            model_name='modelmap',
            constraint=models.UniqueConstraint(fields=('source_model', 'mapper', 'target_model'), name='mappers_modelmap_unique_source_mapper_target'),
        ),
    ]
