# Generated by Django 4.1.4 on 2023-01-12 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_endpoint_domain_and_more'),
        ('mappers', '0005_rename_map_mapper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='integrations.category'),
        ),
    ]
