# Generated by Django 4.1.4 on 2023-01-12 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappers', '0005_rename_map_mapper_and_more'),
        ('integrations', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(help_text='HTTP Method', max_length=8)),
                ('path', models.CharField(help_text='API endpoint path', max_length=64)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='integrations.integration')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mappers.model')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(help_text='Base domain of API', max_length=64)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='integrations.integration')),
            ],
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('integration', 'path', 'method'), name='unique_integration_path_method'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('integration', 'domain'), name='unique_integration_and_domain'),
        ),
    ]
